### ISSUE TITLE
Demo tries to execute non-existant file

### ISSUE THREAD

**Issue by mees** [shubhtuls/mvcSnP#3]
Hi,
when following the demo file to visualize the meshes in https://github.com/shubhtuls/mvcSnP/blob/master/renderer/meshUtils.lua#L206 it tries to open render.sh, which doesn't exist. Maybe renderPose.py is meant? I tried replacing it, but it didn't help.
The error is bash: ../renderer/render.sh: No such file or directory

**Comment by shubhtuls** [comment]
Thanks for catching this! Added the missing file.
