### ISSUE TITLE
Blender obj to EXR file

### ISSUE THREAD

**Issue by qiaogh97** [shubhtuls/mvcSnP#4]
When I execute preprscessing.md , the render_*.png and depth_*.png can't be generated normally. Then I debug BlenderRenderer.py line 93, like this 
(a, b, g, r, dmap) = [fromstr(s, width, height) for s in exrimage.channels('ABGRZ', pt)]
 the (a, b, g, r) are all zero, the dmap's max is 100000000000.0 and min is 1.7825699.
The problem is why (a, b, g, r)  are zero?

**Comment by shubhtuls** [comment]
Does the solution for this [previous issue](https://github.com/shubhtuls/mvcSnP/issues/1) i.e. using Blender 2.71 resolve this for you?

**Comment by qiaogh97** [comment]
Thank you, I didn't see these closed issues, I will have a try immediately. If it works, I will close this issue.

**Comment by qiaogh97** [comment]
Thank you!  It works!
